prepaid-status: improve bad Python version error.
Before:

    $ python2.7 prepaid-status
      File "prepaid-status", line 3
    SyntaxError: Non-ASCII character '\xc2' in file prepaid-status on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python2.7 prepaid-status
      File "prepaid-status", line 11
        ...  # Python 3 is required
        ^
    SyntaxError: invalid syntax